<?php

use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Schema;
use Src\Runtime\Domain\Entities\Gadget;
use Src\Runtime\Domain\Events\GadgetCreatedEvent;
use Src\Runtime\Domain\Exceptions\GadgetNotFound;
use Src\Sandbox\Application\Commands\CreateWidget\CreateWidgetCommand;
use Src\Sandbox\Application\Commands\CreateWidget\CreateWidgetHandler;
use Src\Sandbox\Application\Commands\DeleteWidget\DeleteWidgetCommand;
use Src\Sandbox\Application\Commands\DeleteWidget\DeleteWidgetHandler;
use Src\Sandbox\Application\Commands\UpdateWidget\UpdateWidgetCommand;
use Src\Sandbox\Application\Commands\UpdateWidget\UpdateWidgetHandler;
use Src\Sandbox\Application\Queries\GetWidget\GetWidgetHandler;
use Src\Sandbox\Application\Queries\GetWidget\GetWidgetQuery;
use Src\Sandbox\Application\Queries\ListWidgets\ListWidgetsHandler;
use Src\Sandbox\Application\Queries\ListWidgets\ListWidgetsQuery;
use Src\Sandbox\Application\ReadModels\WidgetReadModel;
use Src\Sandbox\Domain\Events\WidgetCreatedEvent;
use Src\Sandbox\Domain\Exceptions\WidgetNotFound;
use Src\Sandbox\Infrastructure\InMemoryWidgetReadRepository;
use Src\Sandbox\Infrastructure\InMemoryWidgetWriteRepository;

test('scaffolds all files for an entity', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice'])
        ->assertSuccessful();

    // Entity
    expect(file_exists($this->tempDir . '/Billing/Domain/Entities/Invoice.php'))->toBeTrue();

    // Model
    expect(file_exists($this->tempDir . '/Billing/Infrastructure/Models/InvoiceModel.php'))->toBeTrue();

    // Repository interfaces + implementations + mapper
    expect(file_exists($this->tempDir . '/Billing/Domain/Repositories/InvoiceWriteRepository.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Application/Contracts/InvoiceReadRepository.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Infrastructure/InvoiceWriteEloquentRepository.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Infrastructure/InvoiceReadEloquentRepository.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Infrastructure/InvoiceMapper.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Infrastructure/InMemoryInvoiceWriteRepository.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Infrastructure/InMemoryInvoiceReadRepository.php'))->toBeTrue();

    // Read model
    expect(file_exists($this->tempDir . '/Billing/Application/ReadModels/InvoiceReadModel.php'))->toBeTrue();

    // Create command + handler
    expect(file_exists($this->tempDir . '/Billing/Application/Commands/CreateInvoice/CreateInvoiceCommand.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Application/Commands/CreateInvoice/CreateInvoiceHandler.php'))->toBeTrue();

    // Update command + handler
    expect(file_exists($this->tempDir . '/Billing/Application/Commands/UpdateInvoice/UpdateInvoiceCommand.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Application/Commands/UpdateInvoice/UpdateInvoiceHandler.php'))->toBeTrue();

    // Delete command + handler
    expect(file_exists($this->tempDir . '/Billing/Application/Commands/DeleteInvoice/DeleteInvoiceCommand.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Application/Commands/DeleteInvoice/DeleteInvoiceHandler.php'))->toBeTrue();

    // Get query + handler (ReadModel lives in Application/ReadModels, not in Query folder)
    expect(file_exists($this->tempDir . '/Billing/Application/Queries/GetInvoice/GetInvoiceQuery.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Application/Queries/GetInvoice/GetInvoiceHandler.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Application/Queries/GetInvoice/GetInvoiceReadModel.php'))->toBeFalse();

    // List query + handler
    expect(file_exists($this->tempDir . '/Billing/Application/Queries/ListInvoices/ListInvoicesQuery.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Application/Queries/ListInvoices/ListInvoicesHandler.php'))->toBeTrue();

    // Controller, request, resource, sanitizer
    expect(file_exists($this->tempDir . '/Billing/Presentation/Controllers/InvoiceController.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Presentation/Requests/StoreInvoiceRequest.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Presentation/Requests/UpdateInvoiceRequest.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Presentation/Resources/InvoiceResource.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/Billing/Application/Sanitizers/InvoiceSanitizer.php'))->toBeTrue();

    // No unit test generated by scaffold (user creates tests manually)
    expect(file_exists($this->tempDir . '/tests/Unit/Domain/Billing/InvoiceTest.php'))->toBeFalse();
});

test('scaffold passes --force to sub-commands', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true])
        ->assertSuccessful()
        ->expectsOutputToContain('Scaffold for [Invoice] in [Billing] created successfully');
});

test('scaffold wires entity injection in command handler', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    $handlerFile = $this->tempDir . '/Billing/Application/Commands/CreateInvoice/CreateInvoiceHandler.php';
    $content = file_get_contents($handlerFile);

    expect($content)
        ->toContain('use Src\Billing\Domain\Repositories\InvoiceWriteRepository;')
        ->toContain('private readonly InvoiceWriteRepository $repository,');
});

test('scaffold wires entity injection in query handler', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    $handlerFile = $this->tempDir . '/Billing/Application/Queries/GetInvoice/GetInvoiceHandler.php';
    $content = file_get_contents($handlerFile);

    expect($content)
        ->toContain('use Src\Billing\Application\Contracts\InvoiceReadRepository;')
        ->toContain('use Src\Billing\Application\ReadModels\InvoiceReadModel;')
        ->toContain('private readonly InvoiceReadRepository $repository,')
        ->toContain('public function handle(GetInvoiceQuery $query): ?InvoiceReadModel')
        ->toContain('return $this->repository->findById($query->id);');
});

test('scaffold wires list query handler with repository and pagination', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    $handlerFile = $this->tempDir . '/Billing/Application/Queries/ListInvoices/ListInvoicesHandler.php';
    $content = file_get_contents($handlerFile);

    expect($content)
        ->toContain('use CleanArchitecture\Support\PaginatedResult;')
        ->toContain('private readonly InvoiceReadRepository $repository,')
        ->toContain('public function handle(ListInvoicesQuery $query): PaginatedResult')
        ->toContain('return $this->repository->findAll($query->page, $query->perPage);');
});

test('scaffold wires controller with all CQRS handlers', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    $file = $this->tempDir . '/Billing/Presentation/Controllers/InvoiceController.php';
    $content = file_get_contents($file);

    expect($content)
        ->toContain('use Src\Billing\Application\Commands\CreateInvoice\CreateInvoiceHandler;')
        ->toContain('use Src\Billing\Application\Commands\UpdateInvoice\UpdateInvoiceHandler;')
        ->toContain('use Src\Billing\Application\Commands\DeleteInvoice\DeleteInvoiceHandler;')
        ->toContain('use Src\Billing\Application\Queries\GetInvoice\GetInvoiceHandler;')
        ->toContain('use Src\Billing\Application\Queries\ListInvoices\ListInvoicesHandler;')
        ->toContain('private readonly CreateInvoiceHandler $createHandler,')
        ->toContain('private readonly UpdateInvoiceHandler $updateHandler,')
        ->toContain('private readonly DeleteInvoiceHandler $deleteHandler,')
        ->toContain('private readonly GetInvoiceHandler $getHandler,')
        ->toContain('private readonly ListInvoicesHandler $listHandler,')
        ->toContain('$this->listHandler->handle(new ListInvoicesQuery(')
        ->toContain("page: max((int) \$request->query('page', 1), 1)")
        ->toContain('InvoiceResource::collection($result->items)')
        ->toContain('$this->getHandler->handle(new GetInvoiceQuery($id))')
        ->toContain('InvoiceSanitizer::sanitize($request->validated())')
        ->toContain('$id = (string) Str::uuid7();')
        ->toContain('$this->createHandler->handle(new CreateInvoiceCommand($id, $sanitized))')
        ->toContain("->header('Location', \$request->url() . '/' . \$id)")
        ->toContain('$this->updateHandler->handle(new UpdateInvoiceCommand($id, $sanitized))')
        ->toContain('$this->deleteHandler->handle(new DeleteInvoiceCommand($id))');
});

test('scaffold wires crud-specific command constructors and handlers', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    // Create command: array $data constructor, entity create + save handler
    $createCommand = file_get_contents($this->tempDir . '/Billing/Application/Commands/CreateInvoice/CreateInvoiceCommand.php');
    expect($createCommand)->toContain('public array $data,');

    $createHandler = file_get_contents($this->tempDir . '/Billing/Application/Commands/CreateInvoice/CreateInvoiceHandler.php');
    expect($createHandler)
        ->toContain('Invoice::create($command->id)')
        ->toContain('$this->repository->save($entity);')
        ->not->toContain('Illuminate');

    $updateHandler = file_get_contents($this->tempDir . '/Billing/Application/Commands/UpdateInvoice/UpdateInvoiceHandler.php');
    expect($updateHandler)
        ->toContain('$entity = $this->repository->ofId($command->id);')
        ->toContain('throw InvoiceNotFound::withId($command->id);')
        ->toContain('$this->repository->save($entity);');

    // Update command: string $id + array $data constructor
    $updateCommand = file_get_contents($this->tempDir . '/Billing/Application/Commands/UpdateInvoice/UpdateInvoiceCommand.php');
    expect($updateCommand)
        ->toContain('public string $id,')
        ->toContain('public array $data,');

    // Delete command: string $id constructor, repository delete handler
    $deleteCommand = file_get_contents($this->tempDir . '/Billing/Application/Commands/DeleteInvoice/DeleteInvoiceCommand.php');
    expect($deleteCommand)
        ->toContain('public string $id,')
        ->not->toContain('public array $data,');

    $deleteHandler = file_get_contents($this->tempDir . '/Billing/Application/Commands/DeleteInvoice/DeleteInvoiceHandler.php');
    expect($deleteHandler)->toContain('$this->repository->delete($command->id);');
});

test('scaffold wires controller show with null handling', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    $file = $this->tempDir . '/Billing/Presentation/Controllers/InvoiceController.php';
    $content = file_get_contents($file);

    expect($content)->toContain('abort_if(! $readModel, 404)');
});

test('scaffold generates list query as collection', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    $queryFile = $this->tempDir . '/Billing/Application/Queries/ListInvoices/ListInvoicesQuery.php';
    $content = file_get_contents($queryFile);

    expect($content)
        ->toContain('public int $page = 1,')
        ->toContain('public int $perPage = 15,')
        ->not->toContain('public string $id,');
});

test('scaffold wires service provider bindings', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true]);

    $spFile = $this->tempDir . '/Billing/Infrastructure/BillingServiceProvider.php';
    $content = file_get_contents($spFile);

    expect($content)
        ->toContain('InvoiceWriteRepository::class')
        ->toContain('InvoiceWriteEloquentRepository::class')
        ->toContain('InvoiceReadRepository::class')
        ->toContain('InvoiceReadEloquentRepository::class')
        ->not->toContain('TODO: Bind repository interfaces');
});

test('scaffold wires routes with plural kebab-case', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true]);

    $routeFile = $this->tempDir . '/Billing/Presentation/Routes/api.php';
    $content = file_get_contents($routeFile);

    expect($content)
        ->toContain("Route::apiResource('invoices', InvoiceController::class)")
        ->toContain('use Src\Billing\Presentation\Controllers\InvoiceController;');
});

test('scaffold wires web routes with Route::resource', function () {
    $this->artisan('clean:context', ['name' => 'Billing', '--routes' => 'both']);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true]);

    $apiFile = $this->tempDir . '/Billing/Presentation/Routes/api.php';
    $apiContent = file_get_contents($apiFile);
    expect($apiContent)->toContain("Route::apiResource('invoices', InvoiceController::class)");

    $webFile = $this->tempDir . '/Billing/Presentation/Routes/web.php';
    $webContent = file_get_contents($webFile);
    expect($webContent)->toContain("Route::resource('invoices', InvoiceController::class)");
});

test('scaffold warns when service provider has no markers', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);

    // Remove markers from SP
    $spFile = $this->tempDir . '/Billing/Infrastructure/BillingServiceProvider.php';
    $content = file_get_contents($spFile);
    $content = str_replace('// {bindings}', '', $content);
    $content = str_replace('// {/bindings}', '', $content);
    file_put_contents($spFile, $content);

    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true])
        ->expectsOutputToContain('No binding markers');
});

test('scaffold skips wiring when no bounded context exists', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice'])
        ->assertSuccessful()
        ->expectsOutputToContain('ServiceProvider not found');
});

test('scaffold does not duplicate bindings on re-run', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true]);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true]);

    $spFile = $this->tempDir . '/Billing/Infrastructure/BillingServiceProvider.php';
    $content = file_get_contents($spFile);

    expect(substr_count($content, 'InvoiceWriteRepository::class'))->toBe(1);
});

test('scaffold generates migration', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice'])
        ->assertSuccessful()
        ->expectsOutputToContain('Migration created');

    $migrations = File::glob(database_path('migrations') . '/*_create_invoices_table.php');
    expect($migrations)->not->toBeEmpty();

    $content = file_get_contents($migrations[0]);
    expect($content)
        ->toContain("Schema::create('invoices'")
        ->toContain("\$table->uuid('id')->primary()")
        ->toContain('$table->timestamps()');
});

test('scaffold warns when migration already exists', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice'])
        ->expectsOutputToContain('Migration already exists');
});

test('scaffold generates ULID migration, model and create handler with --id-type=ulid', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--id-type' => 'ulid'])
        ->assertSuccessful();

    $migrations = File::glob(database_path('migrations') . '/*_create_invoices_table.php');
    expect($migrations)->not->toBeEmpty();

    expect(file_get_contents($migrations[0]))
        ->toContain("\$table->ulid('id')->primary()")
        ->not->toContain("\$table->uuid('id')");

    expect(file_get_contents($this->tempDir . '/Billing/Infrastructure/Models/InvoiceModel.php'))
        ->toContain('use HasUlids;')
        ->not->toContain('HasUuids');

    expect(file_get_contents($this->tempDir . '/Billing/Presentation/Controllers/InvoiceController.php'))
        ->toContain('$id = (string) Str::ulid();')
        ->not->toContain('Str::uuid7()');
});

test('scaffold honours id_type config across every generated file', function () {
    config()->set('clean-architecture.id_type', 'ulid');

    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice'])
        ->assertSuccessful();

    $migrations = File::glob(database_path('migrations') . '/*_create_invoices_table.php');

    expect(file_get_contents($migrations[0]))->toContain("\$table->ulid('id')->primary()");
    expect(file_get_contents($this->tempDir . '/Billing/Infrastructure/Models/InvoiceModel.php'))
        ->toContain('use HasUlids;');
    expect(file_get_contents($this->tempDir . '/Billing/Presentation/Controllers/InvoiceController.php'))
        ->toContain('$id = (string) Str::ulid();');
});

test('scaffold rejects invalid --id-type value', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--id-type' => 'snowflake'])
        ->expectsOutputToContain("Invalid id type: 'snowflake'")
        ->assertExitCode(2);
});

test('scaffold sanitizer passes through data by default', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    $file = $this->tempDir . '/Billing/Application/Sanitizers/InvoiceSanitizer.php';
    $content = file_get_contents($file);

    expect($content)->toContain('...$data,');

    // The spread must come first so normalized keys override the raw values —
    // spread-last would silently undo any sanitization the user uncomments.
    expect(strpos($content, '...$data,'))->toBeLessThan(strpos($content, 'TODO: Normalize'));
});

test('scaffold --force overwrites the migration instead of duplicating it', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice'])
        ->assertSuccessful();

    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--id-type' => 'ulid', '--force' => true])
        ->assertSuccessful();

    $migrations = File::glob(database_path('migrations') . '/*_create_invoices_table.php');

    expect($migrations)->toHaveCount(1);
    expect(file_get_contents($migrations[0]))
        ->toContain("\$table->ulid('id')->primary()")
        ->not->toContain("\$table->uuid('id')");
});

test('scaffold returns failure exit code on a re-run without --force', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice']);

    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice'])
        ->expectsOutputToContain('completed with warnings')
        ->assertExitCode(1);
});

test('scaffold wires bindings for an entity whose name is a suffix of another', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'SuperUser', '--force' => true]);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'User', '--force' => true]);

    $content = file_get_contents($this->tempDir . '/Billing/Infrastructure/BillingServiceProvider.php');

    expect(substr_count($content, 'Repositories\SuperUserWriteRepository::class'))->toBe(1);
    expect(substr_count($content, 'Repositories\UserWriteRepository::class'))->toBe(1);
});

test('scaffold inserts controller import after the last use statement when the Route import is not an exact match', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);

    $routeFile = $this->tempDir . '/Billing/Presentation/Routes/api.php';
    $content = file_get_contents($routeFile);
    file_put_contents($routeFile, str_replace(
        'use Illuminate\Support\Facades\Route;',
        'use \Illuminate\Support\Facades\Route;',
        $content
    ));

    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true]);

    $wired = file_get_contents($routeFile);

    expect($wired)
        ->toContain('use Src\Billing\Presentation\Controllers\InvoiceController;')
        ->toContain("Route::apiResource('invoices', InvoiceController::class)");
});

test('scaffold falls back to the fully qualified controller name when no import can be placed', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);

    $routeFile = $this->tempDir . '/Billing/Presentation/Routes/api.php';
    $content = file_get_contents($routeFile);
    $content = preg_replace('/^use [^;]+;\n/m', '', $content);
    $content = str_replace('Route::', '\Illuminate\Support\Facades\Route::', $content);
    file_put_contents($routeFile, $content);

    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true])
        ->expectsOutputToContain('Could not add the controller import');

    expect(file_get_contents($routeFile))
        ->toContain('\\Src\\Billing\\Presentation\\Controllers\\InvoiceController::class');
});

test('every scaffolded file is syntactically valid PHP', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true])
        ->assertSuccessful();

    $generated = collect(File::allFiles($this->tempDir))
        ->map(fn ($file) => $file->getPathname())
        ->merge(File::glob(database_path('migrations') . '/*_create_invoices_table.php'))
        ->filter(fn (string $path) => str_ends_with($path, '.php'));

    expect($generated->count())->toBeGreaterThanOrEqual(28);

    foreach ($generated as $path) {
        expect($path)->toBeValidPhp();
    }
});

test('the scaffolded migration actually runs', function () {
    config(['database.default' => 'testing']);

    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice'])
        ->assertSuccessful();

    $this->artisan('migrate', ['--database' => 'testing'])->assertSuccessful();

    expect(Schema::connection('testing')->hasTable('invoices'))->toBeTrue();
    expect(Schema::connection('testing')->hasColumns('invoices', ['id', 'created_at', 'updated_at']))->toBeTrue();
});

test('the scaffolded entity and NotFound exception are executable', function () {
    $this->artisan('clean:scaffold', ['context' => 'Runtime', 'name' => 'Gadget'])
        ->assertSuccessful();

    require_once $this->tempDir . '/Runtime/Domain/Events/GadgetCreatedEvent.php';
    require_once $this->tempDir . '/Runtime/Domain/Entities/Gadget.php';
    require_once $this->tempDir . '/Runtime/Domain/Exceptions/GadgetNotFound.php';

    $entity = Gadget::create('gadget-1');
    expect($entity->id())->toBe('gadget-1');

    $events = $entity->releaseEvents();
    expect($events)->toHaveCount(1)
        ->and($events[0])->toBeInstanceOf(GadgetCreatedEvent::class)
        ->and($events[0]->id)->toBe('gadget-1');
    expect($entity->releaseEvents())->toBe([]);

    expect($entity->equals(Gadget::create('gadget-1')))->toBeTrue();
    expect($entity->equals(Gadget::create('other')))->toBeFalse();

    $exception = GadgetNotFound::withId('gadget-1');
    expect($exception)->toBeInstanceOf(DomainException::class)
        ->and($exception->httpStatus())->toBe(404)
        ->and($exception->getMessage())->toBe('Gadget with id [gadget-1] was not found.');
});

test('scaffold wires files that use Windows line endings', function () {
    $this->artisan('clean:context', ['name' => 'Billing']);

    // Simulate a provider and routes file edited on Windows (CRLF).
    foreach ([
        $this->tempDir . '/Billing/Infrastructure/BillingServiceProvider.php',
        $this->tempDir . '/Billing/Presentation/Routes/api.php',
    ] as $file) {
        file_put_contents($file, str_replace("\n", "\r\n", (string) file_get_contents($file)));
    }

    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--force' => true])
        ->assertSuccessful();

    expect(file_get_contents($this->tempDir . '/Billing/Infrastructure/BillingServiceProvider.php'))
        ->toContain('InvoiceWriteRepository::class');
    expect(file_get_contents($this->tempDir . '/Billing/Presentation/Routes/api.php'))
        ->toContain("Route::apiResource('invoices', InvoiceController::class)");
});

test('generated handlers are unit-testable with the in-memory repositories', function () {
    $this->artisan('clean:scaffold', ['context' => 'Sandbox', 'name' => 'Widget'])
        ->assertSuccessful();

    foreach ([
        'Domain/Events/WidgetCreatedEvent.php',
        'Domain/Entities/Widget.php',
        'Domain/Exceptions/WidgetNotFound.php',
        'Domain/Repositories/WidgetWriteRepository.php',
        'Application/Contracts/WidgetReadRepository.php',
        'Application/ReadModels/WidgetReadModel.php',
        'Infrastructure/InMemoryWidgetWriteRepository.php',
        'Infrastructure/InMemoryWidgetReadRepository.php',
        'Application/Commands/CreateWidget/CreateWidgetCommand.php',
        'Application/Commands/CreateWidget/CreateWidgetHandler.php',
        'Application/Commands/UpdateWidget/UpdateWidgetCommand.php',
        'Application/Commands/UpdateWidget/UpdateWidgetHandler.php',
        'Application/Commands/DeleteWidget/DeleteWidgetCommand.php',
        'Application/Commands/DeleteWidget/DeleteWidgetHandler.php',
        'Application/Queries/GetWidget/GetWidgetQuery.php',
        'Application/Queries/GetWidget/GetWidgetHandler.php',
        'Application/Queries/ListWidgets/ListWidgetsQuery.php',
        'Application/Queries/ListWidgets/ListWidgetsHandler.php',
    ] as $file) {
        require_once $this->tempDir . '/Sandbox/' . $file;
    }

    // The write side, end to end and without a database.
    $writeRepo = new InMemoryWidgetWriteRepository;

    (new CreateWidgetHandler($writeRepo))->handle(new CreateWidgetCommand('w1', ['name' => 'A']));
    $saved = $writeRepo->ofId('w1');
    expect($saved)->not->toBeNull()
        ->and($saved->releaseEvents()[0])->toBeInstanceOf(WidgetCreatedEvent::class);

    (new UpdateWidgetHandler($writeRepo))->handle(new UpdateWidgetCommand('w1', ['name' => 'B']));

    expect(fn () => (new UpdateWidgetHandler($writeRepo))->handle(new UpdateWidgetCommand('missing', [])))
        ->toThrow(WidgetNotFound::class);

    (new DeleteWidgetHandler($writeRepo))->handle(new DeleteWidgetCommand('w1'));
    expect($writeRepo->ofId('w1'))->toBeNull();

    expect(fn () => (new DeleteWidgetHandler($writeRepo))->handle(new DeleteWidgetCommand('w1')))
        ->toThrow(WidgetNotFound::class);

    // The read side, with real pagination semantics.
    $readRepo = new InMemoryWidgetReadRepository([
        new WidgetReadModel('r1'),
        new WidgetReadModel('r2'),
        new WidgetReadModel('r3'),
    ]);

    expect((new GetWidgetHandler($readRepo))->handle(new GetWidgetQuery('r2'))?->id)->toBe('r2');
    expect((new GetWidgetHandler($readRepo))->handle(new GetWidgetQuery('nope')))->toBeNull();

    $page = (new ListWidgetsHandler($readRepo))->handle(new ListWidgetsQuery(page: 2, perPage: 2));
    expect($page->items)->toHaveCount(1)
        ->and($page->items[0]->id)->toBe('r3')
        ->and($page->meta()['total'])->toBe(3)
        ->and($page->meta()['last_page'])->toBe(2);
});

test('scaffold --dry-run lists the plan without writing anything', function () {
    $this->artisan('clean:scaffold', ['context' => 'Billing', 'name' => 'Invoice', '--dry-run' => true])
        ->expectsOutputToContain('Dry run — nothing was written')
        ->assertSuccessful();

    expect(File::glob($this->tempDir . '/Billing/**/*.php'))->toBeEmpty();
    expect(File::glob(database_path('migrations') . '/*_create_invoices_table.php'))->toBeEmpty();
    expect(is_dir($this->tempDir . '/Billing'))->toBeFalse();
});

test('scaffold honours --plural and --table overrides', function () {
    $this->artisan('clean:context', ['name' => 'People']);
    $this->artisan('clean:scaffold', [
        'context' => 'People',
        'name' => 'Person',
        '--plural' => 'People',
        '--table' => 'people',
        '--force' => true,
    ])->assertSuccessful();

    // Class names use the plural override (default inflection would give "Persons").
    expect(file_exists($this->tempDir . '/People/Application/Queries/ListPeople/ListPeopleQuery.php'))->toBeTrue();
    expect(file_exists($this->tempDir . '/People/Application/Queries/ListPersons/ListPersonsQuery.php'))->toBeFalse();

    // Route and table use the overrides too.
    expect(file_get_contents($this->tempDir . '/People/Presentation/Routes/api.php'))
        ->toContain("Route::apiResource('people', PersonController::class)");

    $migrations = File::glob(database_path('migrations') . '/*_create_people_table.php');
    expect($migrations)->toHaveCount(1);

    expect(file_get_contents($this->tempDir . '/People/Infrastructure/Models/PersonModel.php'))
        ->toContain("protected \$table = 'people';");
});
