<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Contexts Path
    |--------------------------------------------------------------------------
    |
    | The directory where bounded contexts are stored, relative to base_path().
    |
    */
    'contexts_path' => 'src',

    /*
    |--------------------------------------------------------------------------
    | Namespace Prefix
    |--------------------------------------------------------------------------
    |
    | The root namespace prefix for all bounded contexts.
    | e.g. Src\Billing, Src\Inventory, etc.
    |
    */
    'namespace_prefix' => 'Src',

    /*
    |--------------------------------------------------------------------------
    | Primary Key Type
    |--------------------------------------------------------------------------
    |
    | The identifier strategy used by generated models, migrations, and
    | create-command handlers. Supported: 'uuid', 'ulid'.
    | Can be overridden per command with the --id-type option.
    |
    */
    'id_type' => 'uuid',

    /*
    |--------------------------------------------------------------------------
    | Render Domain Exceptions
    |--------------------------------------------------------------------------
    |
    | When enabled, uncaught \DomainException instances thrown by your domain
    | layer are rendered as JSON error responses on requests that expect JSON.
    | Exceptions implementing CleanArchitecture\Support\ProvidesHttpStatus
    | choose their own status code; any other \DomainException renders as 422.
    |
    */
    'render_domain_exceptions' => true,

    /*
    |--------------------------------------------------------------------------
    | Auto-discover Contexts
    |--------------------------------------------------------------------------
    |
    | When enabled, the package will automatically discover and register
    | service providers found in each context's Infrastructure directory.
    |
    */
    'auto_discover' => true,

    /*
    |--------------------------------------------------------------------------
    | Auto-load Contexts
    |--------------------------------------------------------------------------
    |
    | When enabled, the package will automatically register PSR-4 autoloading
    | for all bounded contexts in the contexts_path directory.
    |
    */
    'auto_load' => true,

    /*
    |--------------------------------------------------------------------------
    | Architecture Tests Path
    |--------------------------------------------------------------------------
    |
    | The directory where architecture tests are generated, relative to base_path().
    |
    */
    'arch_tests_path' => 'tests/Feature/Architecture',

    /*
    |--------------------------------------------------------------------------
    | Unit Tests Path
    |--------------------------------------------------------------------------
    |
    | The directory where domain unit tests are generated, relative to base_path().
    |
    */
    'unit_tests_path' => 'tests/Unit/Domain',

    /*
    |--------------------------------------------------------------------------
    | Handler Tests Path
    |--------------------------------------------------------------------------
    |
    | Where use-case tests generated by `clean:test --handler` are stored,
    | relative to base_path(). They run against the in-memory repositories.
    |
    */
    'handler_tests_path' => 'tests/Unit/Application',

    /*
    |--------------------------------------------------------------------------
    | Feature Tests Path
    |--------------------------------------------------------------------------
    |
    | Where HTTP feature tests generated by `clean:test --feature` are stored,
    | relative to base_path().
    |
    */
    'feature_tests_path' => 'tests/Feature',

    /*
    |--------------------------------------------------------------------------
    | Custom Stubs Path
    |--------------------------------------------------------------------------
    |
    | Where published (customized) stubs live, relative to base_path(). Stubs
    | found here take precedence over the package defaults.
    |
    */
    'stubs_path' => 'stubs/clean-architecture',
];
