<?php

declare(strict_types=1);

namespace CleanArchitecture\Console;

use Illuminate\Support\Facades\File;

class MakeCommand extends BaseGenerator
{
    protected $signature = 'clean:command {context} {name} {--entity= : Entity name to inject WriteRepository} {--crud= : CRUD operation type (create, update, delete)} {--id-type= : Identifier type generated by create handlers (uuid, ulid)} {--force : Overwrite existing files}';

    protected $description = 'Create a CQRS command with handler';

    public function handle(): int
    {
        $context = $this->argument('context');
        $name = $this->argument('name');
        $entity = $this->option('entity');
        $crud = $this->option('crud');

        $this->validateName($context, 'context');
        $this->validateName($name, 'name');

        if ($entity) {
            $this->validateName($entity, 'entity');
        }

        if ($crud && ! in_array($crud, ['create', 'update', 'delete'])) {
            throw new \InvalidArgumentException(
                "Invalid --crud value: '$crud'. Must be 'create', 'update', or 'delete'."
            );
        }

        // Validation only — ids are generated at the presentation edge, so an
        // invalid --id-type or id_type config still fails fast here.
        $this->resolveIdType();

        $namespace = $this->buildNamespace($context);

        $base = base_path(config('clean-architecture.contexts_path') . "/$context/Application/Commands/$name");
        File::makeDirectory($base, 0755, true, true);

        $commandConstructor = $this->buildCommandConstructor($crud);

        $commandContent = str_replace(
            ['{{Namespace}}', '{{Class}}', '{{CommandConstructor}}'],
            [$namespace, $name, $commandConstructor],
            $this->getStub('command')
        );

        $handlerStub = $this->getStub('command-handler');

        if ($entity) {
            $entityImport = $this->buildEntityImport($namespace, $entity, $crud);
            $entityConstructor = "private readonly {$entity}WriteRepository \$repository,";
            $handlerBody = $this->buildHandlerBody($crud, $entity);

            if (in_array($crud, ['update', 'delete'], true)) {
                $this->ensureNotFoundException($context, $namespace, $entity);
            }
        } else {
            $entityImport = '';
            $entityConstructor = '// TODO: Inject your WriteRepository';
            $handlerBody = '// TODO: Load or create entity, execute domain logic, persist via repository';
        }

        $handlerContent = str_replace(
            ['{{Namespace}}', '{{Class}}', '{{EntityImport}}', '{{EntityConstructor}}', '{{HandlerBody}}'],
            [$namespace, $name, $entityImport, $entityConstructor, $handlerBody],
            $handlerStub
        );

        $wroteCommand = $this->writeFile("$base/{$name}Command.php", $commandContent);
        $wroteHandler = $this->writeFile("$base/{$name}Handler.php", $handlerContent);

        if (! $wroteCommand && ! $wroteHandler) {
            return self::FAILURE;
        }

        $this->info("Command created: $base");

        return self::SUCCESS;
    }

    protected function buildCommandConstructor(?string $crud): string
    {
        return match ($crud) {
            'create' => "public string \$id,\n        public array \$data,",
            'update' => "public string \$id,\n        public array \$data,",
            'delete' => 'public string $id,',
            default => 'public string $id,',
        };
    }

    protected function buildEntityImport(string $namespace, string $entity, ?string $crud): string
    {
        $repository = "use {$namespace}\\Domain\\Repositories\\{$entity}WriteRepository;";

        return match ($crud) {
            'create' => "use {$namespace}\\Domain\\Entities\\{$entity};\n{$repository}",
            'update', 'delete' => "use {$namespace}\\Domain\\Exceptions\\{$entity}NotFound;\n{$repository}",
            default => $repository,
        };
    }

    protected function buildHandlerBody(?string $crud, string $entity): string
    {
        return match ($crud) {
            'create' => "\$entity = {$entity}::create(\$command->id);\n\n"
                . "        // TODO: Apply \$command->data to the entity before saving\n"
                . '        $this->repository->save($entity);',
            'update' => "\$entity = \$this->repository->ofId(\$command->id);\n\n"
                . "        if (! \$entity) {\n"
                . "            throw {$entity}NotFound::withId(\$command->id);\n"
                . "        }\n\n"
                . "        // TODO: Apply changes from \$command->data to the entity\n"
                . '        $this->repository->save($entity);',
            'delete' => "if (! \$this->repository->ofId(\$command->id)) {\n"
                . "            throw {$entity}NotFound::withId(\$command->id);\n"
                . "        }\n\n"
                . '        $this->repository->delete($command->id);',
            default => '// TODO: Load or create entity, execute domain logic, persist via repository',
        };
    }

    /**
     * Update and delete handlers throw {Entity}NotFound — make sure it exists so
     * the generated code never references a class that was not generated.
     */
    protected function ensureNotFoundException(string $context, string $namespace, string $entity): void
    {
        $path = base_path(config('clean-architecture.contexts_path') . "/$context/Domain/Exceptions");
        $file = "$path/{$entity}NotFound.php";

        if (File::exists($file)) {
            return;
        }

        File::makeDirectory($path, 0755, true, true);

        $content = str_replace(
            ['{{Namespace}}', '{{Class}}'],
            [$namespace, $entity],
            $this->getStub('not-found-exception')
        );

        if (File::put($file, $content) === false) {
            $this->components->error("Could not write file: $file");

            return;
        }

        $this->info("Domain exception created: $file");
    }
}
